import type { Metadata } from 'next';
import { LOCALE } from '@/global/constants';
import {
  GentiumBoldTTF,
  GentiumBoldWOFF,
  GentiumBoldWOFF2,
  GentiumRegularTTF,
  GentiumRegularWOFF,
  GentiumRegularWOFF2,
} from '@/global/fonts';
import '@/global/global.scss';
import Footer from '@/components/global/Footer';
import Header from '@/components/global/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={LOCALE}>
      <body
        className={`${GentiumRegularTTF.variable} ${GentiumRegularWOFF.variable} ${GentiumRegularWOFF2.variable} ${GentiumBoldTTF.variable} ${GentiumBoldWOFF.variable} ${GentiumBoldWOFF2.variable}`}
      >
        <Header />
        <main id='main'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
