import type { Metadata } from 'next';
import { LOCALE } from '@/global/constants';
import { GentiumPlus } from '@/global/fonts';
import '@/global/global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={LOCALE}>
      <body className={GentiumPlus.className}>{children}</body>
    </html>
  );
}
